apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-jwt-secret: jwt-secret
    nginx.ingress.kubernetes.io/auth-jwt-verify-key: "key"
    nginx.ingress.kubernetes.io/auth-jwt-login-redirect: "http://$host/auth/login"
    
    nginx.ingress.kubernetes.io/auth-jwt-verify-off: "false"
    nginx.ingress.kubernetes.io/auth-jwt-require: '{"any": true}'
spec:
  ingressClassName: nginx
  rules:
  - host: auth.local
    http:
      paths:
      - path: /auth/login
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 80
      - path: /protected
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 80