apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod

    nginx.ingress.kubernetes.io/auth-jwt: "true"
    nginx.ingress.kubernetes.io/auth-jwt-secret: jwt-secret
    nginx.ingress.kubernetes.io/auth-jwt-key: key
    nginx.ingress.kubernetes.io/auth-jwt-algorithm: HS256
    nginx.ingress.kubernetes.io/auth-jwt-token-header: Authorization
    nginx.ingress.kubernetes.io/auth-jwt-set-headers: "x-user: $jwt_claim_user"

spec:
  rules:
  - http:
      paths:
      - path: /apidocs
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 80
