"""add currencies relationship, renamed table Balance

Revision ID: 6367e70e4fa0
Revises: fd11c14d3a0e
Create Date: 2025-06-29 20:39:44.109160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6367e70e4fa0'
down_revision: Union[str, Sequence[str], None] = 'fd11c14d3a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance', sa.Column('created_at', sa.String(), nullable=False))
    op.drop_constraint(op.f('balance_user_id_key'), 'balance', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('balance_user_id_key'), 'balance', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('balance', 'created_at')
    # ### end Alembic commands ###
