"""Add provider field in device_logins

Revision ID: 8b5ee0a2b141
Revises: eda0238be569
Create Date: 2025-07-04 18:41:13.004336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import MetaData


# revision identifiers, used by Alembic.
revision: str = '8b5ee0a2b141'
down_revision: Union[str, Sequence[str], None] = 'eda0238be569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

metadata = MetaData()

provider_enum = sa.Enum(
    'GOOGLE', 'YANDEX',
    name='oauthprovider',
    metadata=metadata
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    provider_enum.create(op.get_bind())
    op.add_column('device_logins', sa.Column('provider', provider_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_logins', 'provider')
    provider_enum.drop(op.get_bind())
    # ### end Alembic commands ###
