"""Removing the hashed password length limit and adding a default user role value

Revision ID: 98f7f243c57a
Revises: d00c045698b7
Create Date: 2025-06-30 22:23:18.622457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98f7f243c57a'
down_revision: Union[str, Sequence[str], None] = 'd00c045698b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'h_password',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'h_password',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50))
    # ### end Alembic commands ###
