"""Change varchar of transaction_id in user_transactions from 36 to 64

Revision ID: 9a004a8bdffb
Revises: 8b5ee0a2b141
Create Date: 2025-07-07 23:32:49.201563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a004a8bdffb'
down_revision: Union[str, Sequence[str], None] = '8b5ee0a2b141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_transactions', 'transaction_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_transactions', 'transaction_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
