"""double bond between tables

Revision ID: 9f80f56263de
Revises: 6367e70e4fa0
Create Date: 2025-06-29 20:53:02.159016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f80f56263de'
down_revision: Union[str, Sequence[str], None] = '6367e70e4fa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_currencies',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('silver', sa.Integer(), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('silver', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gold', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('balance_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('balance_pkey'))
    )
    op.drop_table('user_currencies')
    # ### end Alembic commands ###
