"""Change the name of the silver column in the UserCurrency table to guild rage

Revision ID: a791d9d76c93
Revises: 98f7f243c57a
Create Date: 2025-07-01 13:12:25.500779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a791d9d76c93'
down_revision: Union[str, Sequence[str], None] = '98f7f243c57a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_currencies', sa.Column('guild_rage', sa.Integer(), nullable=False))
    op.drop_column('user_currencies', 'silver')
    op.alter_column('users', 'h_password',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'h_password',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.add_column('user_currencies', sa.Column('silver', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user_currencies', 'guild_rage')
    # ### end Alembic commands ###
