"""Remove cli_redirect_uri from device_logins table

Revision ID: eda0238be569
Revises: f6af5f59ca20
Create Date: 2025-07-04 18:34:53.623206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda0238be569'
down_revision: Union[str, Sequence[str], None] = 'f6af5f59ca20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_logins', 'cli_redirect_uri')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_logins', sa.Column('cli_redirect_uri', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
